import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers as SessionProviders } from "@/components/SessionProvider/SessionProvider";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Comanda Digital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <SessionProviders>
          {children}
        </SessionProviders>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
